version: '3'

includes:
  html: 
    taskfile: ./pkg/html_extractor/Taskfile.yml
    dir: ./pkg/html_extractor

vars:
  PROJECT_ROOT: "{{.TASKFILE_DIR}}"

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task --list-all
